name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.1.0
  fixnum: ^1.1.0 
  protobuf: ^4.1.1
  file_picker: ^6.0.0      # Pfadwahl zum Speichern
  path_provider: ^2.1.0    # Standard-Downloadordner o. ä.
  ffi: ^2.1.4
  http: ^1.2.0

    # Player
  media_kit: ^1.1.10
  media_kit_video: ^1.2.5
  media_kit_libs_windows_video: ^1.0.11

  # Windows FFI für Named Pipes
  win32: ^5.5.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  protoc_plugin: ^22.5.0

flutter:
  assets:
    - assets/consul-agent-ca.pem
    - assets/medicam-dev-cert.pem
